# FROM node:13.12.0-alpine as build

# WORKDIR /app/frontend

# COPY ./frontend/package.json /app/frontend

# COPY ./frontend/package-lock.json /app/frontend

# RUN npm ci --silent

# COPY ./frontend/ ./

# RUN npm run build

# EXPOSE 3000

# CMD ["npm", "start"]
