# Generated by Django 3.1.7 on 2021-03-10 17:38

import apps.movies.helpers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('avatar', imagekit.models.fields.ProcessedImageField(default=None, null=True, upload_to=apps.movies.helpers.upload_to_actor_image_directory)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(default=None, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('region', models.CharField(blank=True, max_length=30, null=True)),
                ('director', models.CharField(blank=True, max_length=50, null=True)),
                ('poster', imagekit.models.fields.ProcessedImageField(null=True, upload_to=apps.movies.helpers.upload_to_movie_image_directory)),
                ('trailer', models.CharField(blank=True, max_length=255, null=True)),
                ('imdb_rating', models.CharField(blank=True, max_length=4, null=True)),
                ('rm_rating', models.CharField(default=None, max_length=4, null=True)),
                ('slug', models.SlugField(default=None, unique=True)),
                ('actors', models.ManyToManyField(related_name='actors_of_movies', to='movies.Actor')),
                ('genres', models.ManyToManyField(related_name='genres_of_movies', to='movies.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
