# Generated by Django 3.1.3 on 2021-02-04 18:46

import apps.movies.helpers
from django.db import migrations, models
import imagekit.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('region', models.CharField(blank=True, max_length=30, null=True)),
                ('director', models.CharField(blank=True, max_length=50, null=True)),
                ('poster', imagekit.models.fields.ProcessedImageField(null=True, upload_to=apps.movies.helpers.upload_to_movie_image_directory)),
                ('trailer', models.CharField(blank=True, max_length=255, null=True)),
                ('imdb_rating', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
    ]
