# Generated by Django 3.1.7 on 2021-04-09 19:36

import apps.movies.helpers
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='rating',
            new_name='rating_average',
        ),
        migrations.AddField(
            model_name='movie',
            name='rating_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=imagekit.models.fields.ProcessedImageField(default=None, null=True, upload_to=apps.movies.helpers.upload_to_movie_image_directory),
        ),
    ]
