# Generated by Django 3.1.7 on 2021-03-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210310_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='region',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rm_rating',
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_rating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
