# Generated by Django 3.1.7 on 2021-04-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20210409_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default=None, max_length=100, unique=True),
        ),
    ]
