# Generated by Django 3.1.7 on 2021-03-01 19:31

import apps.movies.helpers
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20210204_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rm_rating',
            field=models.CharField(default=None, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default=None, null=True, upload_to=apps.movies.helpers.upload_to_actor_image_directory),
        ),
    ]
