# Generated by Django 3.1.7 on 2021-05-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20210423_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='view_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
