# Generated by Django 3.1.7 on 2021-06-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_movie_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='view_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
