# Generated by Django 3.1.7 on 2021-06-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20210601_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='view_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
