# Generated by Django 3.1.7 on 2021-06-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_auto_20210603_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='view_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
