// constants for choice model field
export const OCCUPATIONS = [
    "Student",
    "PhD Student",
    "Assistant",
    "Researcher",
    "Assistant Professor",
    "Associate Professor",
    "Professor",
    "Head of Department",
    "Head of Faculty",
    "Head of Laboratory",
    "Vice Rector",
    "Rector",
    "Software Developer",
    "Engineer",
    "Technician",
    "Economist",
    "Lawyer",
    "Instructor",
    "Consultant",
    "Manager",
    "Administrator",
    "Analyst",
    "Journalist",
    "Writer",
    "Editor",
    "Librarian",
    "Vice Director",
    "Chief Executive Officer",
    "Retired",
    "Other",
];

export const GENDERS = ["Male", "Female"];

export const GENRES = [
    "Action",
    "Adventure",
    "Animation",
    "Comedy",
    "Crime",
    "Documentary",
    "Drama",
    "Family",
    "Fantasy",
    "Foreign",
    "Game Show",
    "History",
    "Horror",
    "Music",
    "Musical",
    "Mystery",
    "Reality TV",
    "Romance",
    "Sci-Fi",
    "Sports",
    "Superhero",
    "Thriller",
    "TV Movie",
    "War",
    "Western",
];
