# Generated by Django 3.1.7 on 2021-04-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[(None, 'Select your gender'), ('M', 'Male'), ('F', 'Female')], default=None, max_length=30, null=True),
        ),
    ]
