# Generated by Django 3.1.7 on 2021-05-24 14:47

import apps.accounts.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210420_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=apps.accounts.helpers.upload_to_user_avatar_directory),
        ),
    ]
