# Generated by Django 3.1.7 on 2021-06-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210524_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[(None, 'Select your gender'), ('M', 'Male'), ('F', 'Female')], default=None, max_length=1, null=True),
        ),
    ]
