# Generated by Django 3.1.7 on 2021-06-29 19:42

import apps.accounts.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210622_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.helpers.upload_to_user_avatar_directory),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[(None, 'Select your gender'), ('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='occupation',
            field=models.CharField(blank=True, choices=[(None, 'Select your role'), ('Administrator', 'Administrator'), ('Artist', 'Artist'), ('College', 'College'), ('Customer Service', 'Customer Service'), ('Doctor', 'Doctor'), ('Educator', 'Educator'), ('Executive', 'Executive'), ('Farmer', 'Farmer'), ('Homemaker', 'Homemaker'), ('Lawyer', 'Lawyer'), ('Other', 'Other'), ('Programmer', 'Programmer'), ('Retired', 'Retired'), ('Sales', 'Sales'), ('Scientist', 'Scientist'), ('Self-employed', 'Self-employed'), ('Student', 'Student'), ('Technician', 'Technician'), ('Tradesman', 'Tradesman'), ('Unemployed', 'Unemployed'), ('Writer', 'Writer')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
    ]
